[package]
name = "n-body-simulator"
version = "0.1.0"
edition = "2021"
authors = ["Maksym Prymierov <primerovmax@gmail.com>", "Artem Buriak <rodneysgbox@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
